#! /bin/bash

warn() { echo >&2 "WARN: $*"  ; exit 0; }

while read -r old new ref; do
    spec=
    while read -r gitfile; do
        # Skip files in subdir.
        test "$(dirname "$gitfile")" != . && continue

        case $gitfile in
            *.spec)
                test -n "$spec" && warn "multiple specfiles"
                spec=$gitfile
                ;;
        esac
    done <<<"$(git ls-tree -r "$new" --name-only)"
    test -z "$spec" && warn "no specfile found"

    checker=$(dirname "$(readlink -f "$0")")/no-macro-in-changelog
    "$checker" "$spec" "$old" "$new" || exit 1
done
